//
//  CircleModels.swift
//  TraineeTask
//
//  Created by Ramin Akhmad on 13.07.2020.
//  Copyright (c) 2020 Ramin Akhmad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Circle
{
    enum Something
    {
        struct Request
        {
            var cityName: String
        }
        struct Response
        {
            var weatherData: [WeatherResponse]
        }
        struct ViewModel
        {
                var cityName: String
                var temp: [Double]
                var weatherDescription: [String]
            
        }
    }
}
