//
//  CityTablePresenter.swift
//  TraineeTask
//
//  Created by Ramin Akhmad on 14.07.2020.
//  Copyright (c) 2020 Ramin Akhmad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityTablePresentationLogic
{
  func presentSomething(response: CityTable.CityList.Response)
}

class CityTablePresenter: CityTablePresentationLogic
{
  weak var viewController: CityTableDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CityTable.CityList.Response)
  {
    var displayedList = [CityTable.CityList.ViewModel.City]()
    for item in response.cities {
        displayedList.append(CityTable.CityList.ViewModel.City(name: item))
    }
    let viewModel = CityTable.CityList.ViewModel(list: displayedList)
    viewController?.displayTableCityList(viewModel: viewModel)
  }
}
