//
//  CityTableWorker.swift
//  TraineeTask
//
//  Created by Ramin Akhmad on 14.07.2020.
//  Copyright (c) 2020 Ramin Akhmad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CityTableWorker
{
    func fetchCities() -> [String] {
     return ["Odessa","Kiev","Kharkov"]
  }
}
