//
//  CityTableRouter.swift
//  TraineeTask
//
//  Created by Ramin Akhmad on 14.07.2020.
//  Copyright (c) 2020 Ramin Akhmad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CityTableRoutingLogic
{
  func routeToShowCity(segue: UIStoryboardSegue?)
}

protocol CityTableDataPassing
{
  var dataStore: CityTableDataStore? { get }
}

class CityTableRouter: NSObject, CityTableRoutingLogic, CityTableDataPassing
{
  weak var viewController: CityTableViewController?
  var dataStore: CityTableDataStore?
  
  // MARK: Routing
  
  func routeToShowCity(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! CircleViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowCity") as! CircleViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: CityTableViewController, destination: CircleViewController) {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: CityTableDataStore, destination: inout CircleDataStore) {
    let selectedRow =  viewController?.tableView.indexPathForSelectedRow?.row
    destination.name = source.cities?[selectedRow!]
  }
}
