//
//  CityTableModels.swift
//  TraineeTask
//
//  Created by Ramin Akhmad on 14.07.2020.
//  Copyright (c) 2020 Ramin Akhmad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Options {
    case delete
    case add
    case read
}

enum CityTable
{
  // MARK: Use cases
  enum CityList
  {
    struct Request{
        let option: Options
        let name: String
    }
    struct Response{
        let cities: [String]
    }
    struct ViewModel
    {
        struct City {
        let name: String
        }
        var list: [City]
    }
  }
}
